### ISSUE TITLE
Please consider MicroPython

### ISSUE THREAD

**Issue by pfalcon** [AriZuu/picoos-lua#1]
Please consider MicroPython https://github.com/micropython/micropython for picoos port. Unless you really love all "interesting" Lua "features", like lack of proper array/dictionary/objects support, numbering items from arbitrary start values, etc., it may be a better choice. Thanks.

**Comment by AriZuu** [comment]
I'm very much Python fan when it comes to programming in Unix, so I'll definitively have a try on MicroPython also.

**Comment by pfalcon** [comment]
I'm glad you're positive about Python. I found your blog post very interesting, insightful, and helpful, in particular to clarify difference between lwIP and uIP. I also like your work on PicoOS - it's of course sad that it's no longer "officially" maintained, but OTOH, it's a dream project to find a solid base which is no longer changes under your feet, and which doesn't require long committee process to change something if it's worth it ;-).

I hope you will find MicroPython attentively designed and with few neat features too!

**Comment by AriZuu** [comment]
I was able to produce a working python from micropython source code for PicoOS (unix version).
Output from test run:

```
bin/unix-deb/out/mp-test
pico]OS 1.0.4a
Limits: 16 tasks, 16 events
hello world! [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]eol
```

I'll try it later with MSP432 launchpad (as it is the board with biggest RAM I have).

If this all works ok, the result will be a quite nice environment where I can run some tasks
with realtime priorities and script low-priority stuff with python.

**Comment by pfalcon** [comment]
Nice, I knew it wouldn't take much effort, especially for unix version! Note that uPy is quite optimized for memory usage. You can try that with unix version using "-X heapsize=2K" switch (for 2K, make sure you build 32-bit version). It will allow not just run single statements, but even simple functions. That's all with parser and compiler memory usage of course. Try that with Lua ;-). Of course, requirement for "lazy" Python (i.e. writing programs in a way you do on desktop) programming are much higher.

So, please feel free to stay in touch - via https://github.com/micropython/micropython/issues , http://forum.micropython.org/ or otherwise.

**Comment by AriZuu** [comment]
I got also Arm Cortex-M version compiled last night, but didn't have time to actually try it with real hardware. But I'll try soon.

**Comment by AriZuu** [comment]
Got MicroPython running on TI MSP432 launchpad. For details, see http://stonepile.fi/python-lua-for-picoos/

**Comment by pfalcon** [comment]
Something I also wanted to mention, because I'm not sure how visible it is (feedback on that is appreciated) - uPy includes just few modules, which are deemed to be "core", like array and struct. But there's sister project to provide as complete as makes sense Python standard library - https://github.com/micropython/micropython-lib . It mostly targets "unix" port, but modules which don't deal with POSIX i/o should be usable on bare-metal too (many are reimplemented from scratch rather than ported from CPython, to be lean). There's also frozen modules support to package Python modules into monolithic binary: https://github.com/micropython/micropython/commit/640e0b221e972f9a2da2d870bf3fc5a93c18f0ec

**Comment by AriZuu** [comment]
I noticed micropython-lib, but didn't try to include stuff from there yet. Pico]OS has possibility for Posix IO on newlib+gcc -toolchain environments (Arm Cortex-M, Arm LPC2xxx) and also on PIC32. I have had glue code for newlib syscall layer and Fat FS in an old project of mine - I started committing it into
picoos-micro library as will make use of third party stuff easier (for example MicroPython).

I was already wondering how to package python modules into flashable binary, The frozen module support is a solution to that, isn't it ?

**Comment by pfalcon** [comment]
> I was already wondering how to package python modules into flashable binary, The frozen module support is a solution to that, isn't it ?

Yes, exactly. And the whole concept is taken from CPython (but implementation details of course differ):

https://docs.python.org/3/c-api/import.html#c._frozen
